name: Run Test

on:
  push:
    branches: [ ubuntu-latest ]

    pull_request:
      branches:
        - develop
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: make executable gradlew
        run: chmod +x ./gradlew

      - name: run unittest
        run: ./gradlew clean test
